name: Display Inputs Action
description: Display workflow_dispatch inputs as a table in GitHub Job Summary
author: Yuki Sakai

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: list
  color: blue

inputs:
  github-token:
    description: 'GitHub token for accessing workflow information'
    required: false
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
