name: Test Workflow with Inputs
permissions:
  contents: read

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: This is a test workflow that intentionally has inputs to test the display-inputs-action functionality
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development
      version:
        description: 'Version Number'
        required: true
        type: string
      enable-debug:
        description: 'Enable Debug Mode'
        required: false
        type: boolean
        default: false
      log-level:
        description: 'Log Level'
        required: false
        type: choice
        options:
          - info
          - warn
          - error
          - debug
        default: info
      notes:
        description: 'Additional Notes'
        required: false
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  test-display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Display workflow inputs
        id: display-inputs
        # zizmor:ignore[unpinned-uses] - This is a test workflow for our own action
        uses: VeyronSakai/display-inputs-action@main

      - name: Print inputs
        id: print-inputs
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          VERSION: ${{ inputs.version }}
          ENABLE_DEBUG: ${{ inputs.enable-debug }}
          LOG_LEVEL: ${{ inputs.log-level }}
          NOTES: ${{ inputs.notes }}
        run: |
          Write-Host "=== Workflow Inputs ==="
          Write-Host "Environment: $env:ENVIRONMENT"
          Write-Host "Version: $env:VERSION"
          Write-Host "Enable Debug: $env:ENABLE_DEBUG"
          Write-Host "Log Level: $env:LOG_LEVEL"
          Write-Host "Notes: $env:NOTES"
