name: Test Workflow without Inputs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        id: test-step
        run: echo "This workflow has no inputs"

      - name: Display workflow inputs
        id: display-inputs
        # zizmor:ignore[unpinned-uses] - This is a test workflow for our own action
        uses: VeyronSakai/display-inputs-action@main
