name: Test Workflow with Inputs
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
        default: development
      version:
        description: 'Version Number'
        required: true
        type: string
      enable-debug:
        description: 'Enable Debug Mode'
        required: false
        type: boolean
        default: false
      log-level:
        description: 'Log Level'
        required: false
        type: choice
        options:
          - info
          - warn
          - error
          - debug
        default: info
      notes:
        description: 'Additional Notes'
        required: false
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  test-display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Display workflow inputs
        id: display-inputs
        uses: ./

      - name: Print inputs
        id: print-inputs
        run: |
          Write-Host "=== Workflow Inputs ==="
          Write-Host "Environment: ${{ inputs.environment }}"
          Write-Host "Version: ${{ inputs.version }}"
          Write-Host "Enable Debug: ${{ inputs.enable-debug }}"
          Write-Host "Log Level: ${{ inputs.log-level }}"
          Write-Host "Notes: ${{ inputs.notes }}"
